# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestFirstlinkedin():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(
            "/home/ritika/Documents/selenium-env/env/chromedriver")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_firstlinkedin(self):
        self.driver.get("https://www.linkedin.com/in/ritika-singh-416544191/")
        self.driver.set_window_size(1366, 734)
        for i in range(3):
            self.driver.execute_script("window.scrollTo(0,572)")
            self.driver.execute_script("window.scrollTo(0,939)")
            self.driver.execute_script("window.scrollTo(0,1076)")
            self.driver.execute_script("window.scrollTo(0,2879)")
            self.driver.execute_script("window.scrollTo(0,3527)")
            self.driver.execute_script("window.scrollTo(0,3948)")
            self.driver.find_element(By.ID, "ember25").click()
            self.driver.execute_script("window.scrollTo(0,0)")
            self.driver.execute_script("window.scrollTo(0,102)")
            self.driver.execute_script("window.scrollTo(0,978)")
            self.driver.find_element(
                By.CSS_SELECTOR, "#ember2231 > .pv-dashboard-section__metric-count").click()
            self.driver.execute_script("window.scrollTo(0,745)")
            self.driver.execute_script("window.scrollTo(0,0)")


obj = TestFirstlinkedin()
obj.setup_method
obj.teardown_method
obj.test_firstlinkedin
